export class UserRegistration {
    id:number=0;
    btype:string="";
	customerName:string="";
	age:number=0;
	email:string="";
	password:string="";
	dateOfBirth:string="";
	height:string="";
	religion:string="";
	subcast:string="";
	country:string="";
	income:string="";
	education:string="";
	profession:string="";
	familyDetails:string="";
	status:string="";
	subcription:string="";
	substard:string="";
	subend:string="";
    contact:string="";
	maritalstatus:string="";
}
